/**
 * Parsing Methods Identity Cards Catalog
 * Enterprise Document Intelligence [Vol.1 #5nonies]
 * Standardized cards across 4 families: Blue (Native), Teal (Layout), Amber (OCR), Violet (Structure).
 */

export const PARSING_FAMILIES = [
  { id: 'all', name: 'All Families', color: '#64748b', icon: '🌐' },
  { id: 'native', name: 'Native Text Parsers', color: '#2563eb', icon: '📄', desc: 'Direct text layer extraction with zero model overhead' },
  { id: 'layout', name: 'Layout & Table Models', color: '#0d9488', icon: '📊', desc: 'Deep learning layout passes for nested cell and grid parsing' },
  { id: 'ocr', name: 'OCR Readers', color: '#d97706', icon: '🔍', desc: 'Pixel-level character recognition for scanned pages' },
  { id: 'structure', name: 'Structure & TOC Recovery', color: '#7c3aed', icon: '📐', desc: 'Hierarchical outline reconstruction from typography and summaries' },
];

export const PARSER_IDENTITY_CARDS = [
  // ── Blue: Native Text Parsers ─────────────────────────────────────────────
  {
    id: 'fitz',
    name: 'PyMuPDF (fitz)',
    family: 'native',
    familyLabel: 'Native Text Parser',
    color: '#2563eb',
    badgeColor: 'rgba(37, 99, 235, 0.15)',
    license: 'AGPL-3.0',
    runs: 'Local / CPU',
    speed: '⚡ <10ms/page',
    callsLlm: false,
    preservesStyle: true,
    targetInput: 'Digital PDF binary with extractable text layer',
    primaryOutput: 'line_df, span_df with typography coordinates',
    summary: 'The rock-solid baseline of every enterprise pipeline. Reads font sizes, weights, bounding boxes, and native bookmarks in sub-millisecond execution.',
    strengths: [
      'Unmatched raw throughput (<10ms per page)',
      'Granular font name, size, flags (bold/italic), and color preservation',
      'Zero GPU or network requirements',
      'Exposes raw textpage dict and embedded outline',
    ],
    weaknesses: [
      'Blind to multi-column reading order ruptures without layout heuristics',
      'Cannot extract complex cell boundaries in borderless tables',
      'Fails completely on scanned raster documents',
    ],
    idealFor: 'Mandatory first step for every digital PDF document.',
  },
  {
    id: 'pymupdf4llm',
    name: 'PyMuPDF4LLM',
    family: 'native',
    familyLabel: 'Native Text Parser',
    color: '#2563eb',
    badgeColor: 'rgba(37, 99, 235, 0.15)',
    license: 'AGPL-3.0',
    runs: 'Local / CPU',
    speed: '⚡ <15ms/page',
    callsLlm: false,
    preservesStyle: false,
    targetInput: 'Digital PDF document',
    primaryOutput: 'Clean RAG-ready Markdown with table formatting',
    summary: 'Higher-level PyMuPDF wrapper that converts native text layers directly into formatted markdown chunks ready for vector embeddings.',
    strengths: [
      'Fast single-call markdown generation',
      'Handles basic 2-column flow and header identification',
      'Lightweight and pure Python with zero heavy weights',
    ],
    weaknesses: [
      'Discards raw font bounding boxes and span metrics',
      'Cannot provide fine-grained line_df coordinates for visual PDF overlays',
    ],
    idealFor: 'Rapid ingestion into vector RAG when bounding box provenance is not required.',
  },
  {
    id: 'pdfplumber',
    name: 'pdfplumber',
    family: 'native',
    familyLabel: 'Native Text Parser',
    color: '#2563eb',
    badgeColor: 'rgba(37, 99, 235, 0.15)',
    license: 'MIT',
    runs: 'Local / CPU',
    speed: '🟡 ~50ms/page',
    callsLlm: false,
    preservesStyle: true,
    targetInput: 'Digital PDF with ruled/bordered forms and tables',
    primaryOutput: 'Exact cell coordinates and line intersections',
    summary: 'Precision coordinate inspector built on pdfminer.six, designed specifically for extracting ruled tables and form fields via geometric edge detection.',
    strengths: [
      'Exceptional extraction of ruled tables with visible horizontal/vertical lines',
      'Precise visual debugging of bounding boxes and character curves',
      'Permissive MIT license',
    ],
    weaknesses: [
      'Struggles with whitespace-only borderless tables',
      '5x slower than PyMuPDF on dense prose documents',
    ],
    idealFor: 'Invoices, purchase orders, and structured forms with visible grid lines.',
  },
  {
    id: 'pdfminer',
    name: 'pdfminer.six',
    family: 'native',
    familyLabel: 'Native Text Parser',
    color: '#2563eb',
    badgeColor: 'rgba(37, 99, 235, 0.15)',
    license: 'MIT',
    runs: 'Local / CPU',
    speed: '🟡 ~80ms/page',
    callsLlm: false,
    preservesStyle: true,
    targetInput: 'Low-level PDF streams & anomalous font encodings',
    primaryOutput: 'LTComponent character tree and layout coordinates',
    summary: 'The classic low-level Python PDF layout engine. Provides character-level geometric analysis and deep font CID decoding.',
    strengths: [
      'Handles esoteric font encodings and non-standard CID mappings',
      'Pure Python with zero C bindings',
    ],
    weaknesses: [
      'High latency on 100+ page documents',
      'Complex API requiring custom tree traversal logic',
    ],
    idealFor: 'Low-level font recovery and deep coordinate debugging.',
  },

  // ── Teal: Layout & Table Models ───────────────────────────────────────────
  {
    id: 'docling',
    name: 'Docling (IBM)',
    family: 'layout',
    familyLabel: 'Layout & Table Model',
    color: '#0d9488',
    badgeColor: 'rgba(13, 148, 136, 0.15)',
    license: 'MIT',
    runs: 'Local / GPU-opt',
    speed: '🟠 ~400ms/page',
    callsLlm: false,
    preservesStyle: false,
    targetInput: 'PDFs with complex nested, multi-column, or borderless tables',
    primaryOutput: 'Hierarchical DoclingDocument, Table JSON & Markdown',
    summary: 'State-of-the-art open-source layout analysis and table structure recognition model from IBM Research. Resolves multi-row merged cells without cloud upload.',
    strengths: [
      'Superb accuracy on complex, borderless, and multi-tier merged cell tables',
      'Runs locally with zero external data transmission (HIPAA / GDPR compliant)',
      'Outputs rich DoclingDocument AST with reading order and code blocks',
    ],
    weaknesses: [
      'Requires PyTorch / ONNX runtime and GPU for optimal throughput',
      'Higher memory footprint during layout pass',
    ],
    idealFor: 'Financial statements, SEC 10-K filings, and rate tables requiring cell-level precision.',
  },
  {
    id: 'azure_layout',
    name: 'Azure AI Document Intelligence',
    family: 'layout',
    familyLabel: 'Layout & Table Model',
    color: '#0d9488',
    badgeColor: 'rgba(13, 148, 136, 0.15)',
    license: 'Commercial API',
    runs: 'Cloud API',
    speed: '🟠 ~500ms/page',
    callsLlm: false,
    preservesStyle: true,
    targetInput: 'Complex enterprise documents, scans, and multi-lingual reports',
    primaryOutput: 'Polygon coordinates, Key-Value pairs, Table cells',
    summary: 'Microsoft enterprise cloud document parser with battle-tested layout recognition, key-value pair detection, and high-accuracy OCR.',
    strengths: [
      'Zero local GPU management or infrastructure overhead',
      'Extracts key-value pairs (form fields) automatically',
      'Handles skewed, rotated, and mixed digital/scanned pages seamlessly',
    ],
    weaknesses: [
      'Recurring cloud API cost ($1.50 - $10 per 1k pages)',
      'Requires cloud upload (unacceptable for air-gapped sovereign environments)',
    ],
    idealFor: 'Enterprise cloud workflows with diverse, unstandardized document formats.',
  },
  {
    id: 'mineru',
    name: 'MinerU (Magic-PDF)',
    family: 'layout',
    familyLabel: 'Layout & Table Model',
    color: '#0d9488',
    badgeColor: 'rgba(13, 148, 136, 0.15)',
    license: 'AGPL-3.0',
    runs: 'Local / GPU',
    speed: '🔴 ~1000ms/page',
    callsLlm: false,
    preservesStyle: true,
    targetInput: 'Academic papers with heavy mathematical equations and LaTeX formulas',
    primaryOutput: 'LaTeX equations, Tables, Clean Markdown AST',
    summary: 'Specialized deep learning parser designed for academic papers. Translates inline and display math formulas into clean LaTeX code alongside layout structure.',
    strengths: [
      'Industry-leading LaTeX equation recognition and extraction',
      'Removes running headers, footers, and watermark noise automatically',
    ],
    weaknesses: [
      'Heavy GPU requirements (VRAM > 8GB)',
      'Slow execution compared to lightweight native parsers',
    ],
    idealFor: 'arXiv papers, mathematics textbooks, and scientific research publications.',
  },
  {
    id: 'surya',
    name: 'Surya (VikParuchuri)',
    family: 'layout',
    familyLabel: 'Layout & Table Model',
    color: '#0d9488',
    badgeColor: 'rgba(13, 148, 136, 0.15)',
    license: 'GPL-3.0',
    runs: 'Local / GPU',
    speed: '🟠 ~300ms/page',
    callsLlm: false,
    preservesStyle: false,
    targetInput: 'Multi-column, complex magazine or publication layouts',
    primaryOutput: 'Reading order flow, Line bboxes, Layout classification',
    summary: 'Modern multilingual layout analysis and reading order detection model. Accurately determines the sequence in which multi-column text should be read.',
    strengths: [
      'Solves complex multi-column reading order errors',
      'Multilingual support across 90+ languages',
      'Modular layout, line detection, and OCR blocks',
    ],
    weaknesses: [
      'Table cell recognition is less granular than Docling',
    ],
    idealFor: 'Multi-column academic papers, newspapers, and magazines.',
  },

  // ── Amber: OCR Readers ───────────────────────────────────────────────────
  {
    id: 'easyocr',
    name: 'EasyOCR (JaidedAI)',
    family: 'ocr',
    familyLabel: 'OCR Reader',
    color: '#d97706',
    badgeColor: 'rgba(217, 119, 6, 0.15)',
    license: 'Apache-2.0',
    runs: 'Local / GPU-opt',
    speed: '🔴 ~800ms/page',
    callsLlm: false,
    preservesStyle: false,
    targetInput: 'Scanned pages, raster images, low-res PDFs',
    primaryOutput: 'Word bounding boxes and text strings',
    summary: 'Popular open-source OCR engine with 80+ supported languages. Extracts raw text and bounding boxes from pixel grids when no digital font layer exists.',
    strengths: [
      'Completely free and open-source (Apache 2.0)',
      'Supports 80+ language scripts out of the box',
      'Simple Python integration',
    ],
    weaknesses: [
      'Outputs words, not documents (no typography or native outline semantics)',
      'Computationally heavy on CPU; requires GPU for high throughput',
    ],
    idealFor: 'Scanned documents in cost-sensitive, offline environments.',
  },
  {
    id: 'paddleocr',
    name: 'PaddleOCR',
    family: 'ocr',
    familyLabel: 'OCR Reader',
    color: '#d97706',
    badgeColor: 'rgba(217, 119, 6, 0.15)',
    license: 'Apache-2.0',
    runs: 'Local / GPU-opt',
    speed: '🟠 ~400ms/page',
    callsLlm: false,
    preservesStyle: false,
    targetInput: 'Scanned receipts, rotated pages, multilingual documents',
    primaryOutput: 'Rotated text bboxes, confidence scores, PP-Structure tables',
    summary: 'Ultra-fast and highly accurate OCR system featuring PP-Structure for layout and table reconstruction directly from pixels.',
    strengths: [
      'High accuracy on rotated, curved, and degraded text',
      'PP-Structure extracts basic table structures from scans',
      'Exceptional performance on Asian language scripts (CJK)',
    ],
    weaknesses: [
      'Complex C++/PaddlePaddle dependency stack',
    ],
    idealFor: 'Scanned receipts, bills of lading, and multilingual Asian documents.',
  },
  {
    id: 'mistral_ocr',
    name: 'Mistral OCR',
    family: 'ocr',
    familyLabel: 'OCR Reader',
    color: '#d97706',
    badgeColor: 'rgba(217, 119, 6, 0.15)',
    license: 'Commercial API',
    runs: 'Cloud API',
    speed: '🟠 ~350ms/page',
    callsLlm: true,
    preservesStyle: true,
    targetInput: 'Complex scanned pages with tables, math, and headers',
    primaryOutput: 'End-to-end semantic Markdown with embedded tables',
    summary: 'Frontier multimodal OCR API from Mistral AI. Transcribes raw page images directly into formatted Markdown with math equations and table grids.',
    strengths: [
      'Direct-to-Markdown transcription preserving semantic hierarchy',
      'High speed cloud inference',
      'Handles mixed text, formulas, and tabular regions in single pass',
    ],
    weaknesses: [
      'Cloud API cost per page',
      'Token context limits on very large composite documents',
    ],
    idealFor: 'Scanned reports requiring immediate Markdown conversion without multistage pipelines.',
  },

  // ── Violet: Structure & TOC Recovery ──────────────────────────────────────
  {
    id: 'toc_sommaire',
    name: 'TOC Sommaire Cascade',
    family: 'structure',
    familyLabel: 'Structure & TOC Recovery',
    color: '#7c3aed',
    badgeColor: 'rgba(124, 58, 237, 0.15)',
    license: 'Custom / Open',
    runs: 'Local / CPU',
    speed: '⚡ <20ms/page',
    callsLlm: false,
    preservesStyle: true,
    targetInput: 'PDF with printed Table of Contents (dot-leader lines)',
    primaryOutput: 'toc_df (level, title, start_page, end_page)',
    summary: 'Deterministic regex cascade from Article 5septies that parses dot-leader lines ("Introduction ........ 12") on early pages to reconstruct the exact outline.',
    strengths: [
      'Zero LLM cost and instantaneous deterministic execution',
      'Captures exact author-intended section page mappings',
    ],
    weaknesses: [
      'Fails when document lacks a printed contents page (e.g. arXiv preprints)',
    ],
    idealFor: 'Annual reports, policy documents, and manuals with printed TOC pages.',
  },
  {
    id: 'toc_body_structure',
    name: 'TOC Body Typography Loop',
    family: 'structure',
    familyLabel: 'Structure & TOC Recovery',
    color: '#7c3aed',
    badgeColor: 'rgba(124, 58, 237, 0.15)',
    license: 'Custom / Open',
    runs: 'Local + LLM Leaf',
    speed: '🟡 ~150ms/page',
    callsLlm: true,
    preservesStyle: true,
    targetInput: 'PDFs with no TOC page and no native bookmarks',
    primaryOutput: 'Validated relational toc_df with scope boundaries',
    summary: 'The flagship Case 4 engine from Article 5octies. Proposes candidate headings via 6 span typography signals, validated through a bounded LLM loop.',
    strengths: [
      'Reconstructs TOC for documents with zero existing outline metadata',
      'Rules propose, LLM validates — bounded loop prevents hallucination',
      'Standard relational toc_df schema with start_page and end_page scopes',
    ],
    weaknesses: [
      'Requires 1-2 small LLM calls for heading verification',
    ],
    idealFor: 'Scientific papers, contracts, and memos with body-only headings.',
  },
  {
    id: 'vision_figures',
    name: 'Vision LLM Figures',
    family: 'structure',
    familyLabel: 'Multimodal Parsing',
    color: '#ec4899',
    badgeColor: 'rgba(236, 72, 153, 0.15)',
    license: 'Cloud API',
    runs: 'Cloud API',
    speed: '🔴 ~1500ms/fig',
    callsLlm: true,
    preservesStyle: false,
    targetInput: 'Embedded charts, flowcharts, heatmaps, architecture diagrams',
    primaryOutput: 'image_df with structured summaries & data points',
    summary: 'Multimodal vision model reader that inspects high-resolution visual figure crops and transcribes data charts and architectural flowcharts into queryable text.',
    strengths: [
      'Makes image charts and visual diagrams searchable for vector RAG',
      'Extracts numerical data points from plotted graphs',
    ],
    weaknesses: [
      'API cost per visual image call ($0.005 - $0.02 per image)',
      'Higher latency',
    ],
    idealFor: 'Technical papers and analyst reports with rich charts and infographics.',
  },
];
