/**
 * Sample PDF Presets for Interactive Benchmarking & Simulation
 * Enterprise Document Intelligence [Vol.1 #5nonies]
 */

export const SAMPLE_BENCHMARK_PDFS = [
  {
    id: 'attention-paper',
    title: 'Attention Is All You Need (1706.03762v7.pdf)',
    subtitle: 'Vaswani et al. — NeurIPS 2017 Canonical Publication',
    tag: 'Article Section 4 Benchmark',
    type: 'Academic Paper / Multimodal',
    pageCount: 15,
    fileSize: '2.1 MB',
    description: '15-page NIPS paper with native outline, model architecture diagram, and WMT translation benchmark tables.',
    natureProfile: {
      is_scanned: false,
      has_native_outline: true,
      has_sommaire: false,
      is_composite: false,
      has_rich_figures: true,
      has_tables_signal: true,
      label: 'rich-multimodal-paper',
      desc: 'Complex publication with native bookmarks, embedded tables, and figures',
    },
    metrics: {
      totalLines: 1048,
      totalSpans: 3480,
      linesPerPage: 69.87,
      nativeBookmarksCount: 15,
      figureCount: 5,
      tableCount: 4,
    },
    nativeBookmarks: [
      { level: 1, title: 'Abstract', page: 1 },
      { level: 1, title: '1. Introduction', page: 1 },
      { level: 1, title: '2. Background', page: 2 },
      { level: 1, title: '3. Model Architecture', page: 2 },
      { level: 2, title: '3.1 Encoder and Decoder Stacks', page: 2 },
      { level: 2, title: '3.2 Attention', page: 3 },
      { level: 2, title: '3.3 Position-wise Feed-Forward Networks', page: 5 },
      { level: 2, title: '3.4 Embeddings and Softmax', page: 5 },
      { level: 2, title: '3.5 Positional Encoding', page: 6 },
      { level: 1, title: '4. Why Self-Attention', page: 6 },
      { level: 1, title: '5. Training', page: 7 },
      { level: 1, title: '6. Results', page: 8 },
      { level: 1, title: '7. Conclusion', page: 10 },
      { level: 1, title: 'References', page: 11 },
      { level: 1, title: 'Attention Visualizations', page: 13 },
    ],
    sampleLines: [
      { page: 1, size: 18, font: 'Times-Bold', flags: 16, text: 'Attention Is All You Need' },
      { page: 1, size: 10, font: 'Times-Roman', flags: 0, text: 'Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit' },
      { page: 1, size: 12, font: 'Times-Bold', flags: 16, text: 'Abstract' },
      { page: 1, size: 9.5, font: 'Times-Roman', flags: 0, text: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks.' },
      { page: 1, size: 13, font: 'Times-Bold', flags: 16, text: '1. Introduction' },
      { page: 2, size: 13, font: 'Times-Bold', flags: 16, text: '2. Background' },
      { page: 2, size: 13, font: 'Times-Bold', flags: 16, text: '3. Model Architecture' },
      { page: 3, size: 11, font: 'Times-Bold', flags: 16, text: '3.2.1 Scaled Dot-Product Attention' },
      { page: 4, size: 11, font: 'Times-Bold', flags: 16, text: '3.2.2 Multi-Head Attention' },
      { page: 8, size: 13, font: 'Times-Bold', flags: 16, text: '6. Results' },
      { page: 8, size: 9, font: 'Courier', flags: 0, text: 'Model                  BLEU (EN-DE)   BLEU (EN-FR)   Training Cost (FLOPs)' },
      { page: 8, size: 9, font: 'Courier', flags: 0, text: 'ByteNet [18]           23.75          -              -                    ' },
      { page: 8, size: 9, font: 'Courier', flags: 0, text: 'Deep-Att + PosUnk [39] -              39.2           -                    ' },
      { page: 8, size: 9, font: 'Courier', flags: 0, text: 'Transformer (base)     27.3           38.1           3.3e18               ' },
      { page: 8, size: 9, font: 'Courier', flags: 0, text: 'Transformer (big)      28.4           41.8           2.3e19               ' },
    ],
    sampleFigures: [
      { id: 'fig-1', page: 3, title: 'Figure 1: The Transformer - model architecture', type: 'architecture_diagram', summary: 'Schematic showing stacked self-attention and point-wise fully connected layers for encoder and decoder.' },
      { id: 'fig-2', page: 4, title: 'Figure 2: (left) Scaled Dot-Product Attention (right) Multi-Head Attention', type: 'flowchart', summary: 'Block diagram detailing Q, K, V projection matrices, scale dot-product softmax, and concatenation.' },
    ],
  },
  {
    id: 'scanned-invoice',
    title: 'Scanned Medical Equipment Invoice & Claims Form',
    subtitle: 'Legacy Hospital Billing Archive (1998)',
    tag: 'OCR Path Benchmark',
    type: 'Scanned Raster PDF',
    pageCount: 3,
    fileSize: '4.8 MB',
    description: 'Scanned 200-DPI photocopied medical claim form with zero digital text layer and skewed skew angle.',
    natureProfile: {
      is_scanned: true,
      has_native_outline: false,
      has_sommaire: false,
      is_composite: false,
      has_rich_figures: false,
      has_tables_signal: true,
      label: 'scanned-image',
      desc: 'Scanned PDF with minimal or no extracted text layer; requires OCR',
    },
    metrics: {
      totalLines: 0,
      totalSpans: 0,
      linesPerPage: 0.0,
      nativeBookmarksCount: 0,
      figureCount: 3,
      tableCount: 1,
    },
    nativeBookmarks: [],
    sampleLines: [],
    sampleFigures: [],
  },
  {
    id: 'master-tariff-contract',
    title: '200-Page Master Logistics & Tariff Rate Agreement',
    subtitle: 'Enterprise Procurement Contract with Nested Surcharges',
    tag: 'Table Model Benchmark',
    type: 'Legal Contract / Table Heavy',
    pageCount: 184,
    fileSize: '12.4 MB',
    description: 'Dozens of multi-tier shipping tariff tables, fuel adjustment matrices, and regulatory compliance riders.',
    natureProfile: {
      is_scanned: false,
      has_native_outline: true,
      has_sommaire: false,
      is_composite: false,
      has_rich_figures: false,
      has_tables_signal: true,
      label: 'table-heavy-document',
      desc: 'Report or agreement with dense tabular data structures',
    },
    metrics: {
      totalLines: 14200,
      totalSpans: 48000,
      linesPerPage: 77.17,
      nativeBookmarksCount: 42,
      figureCount: 0,
      tableCount: 68,
    },
    nativeBookmarks: [
      { level: 1, title: '1. Definitions and Scope', page: 1 },
      { level: 1, title: '2. Rate Schedules & Base Tariffs', page: 12 },
      { level: 2, title: '2.1 Zone A Intermodal Rates', page: 14 },
      { level: 2, title: '2.2 Zone B Ocean Freight Surcharges', page: 28 },
      { level: 1, title: '3. Fuel Adjustment Calculation Formula', page: 45 },
    ],
    sampleLines: [
      { page: 14, size: 10, font: 'Helvetica', flags: 0, text: 'Origin Zone     Dest Zone     20ft Container     40ft HC Container     Peak Surcharge' },
      { page: 14, size: 9, font: 'Helvetica', flags: 0, text: 'US-WEST         EU-NORTH      $2,450             $3,890                $450' },
      { page: 14, size: 9, font: 'Helvetica', flags: 0, text: 'US-EAST         APAC-SOUTH    $1,980             $3,200                $380' },
      { page: 14, size: 9, font: 'Helvetica', flags: 0, text: 'LATAM-BRA       EU-WEST       $2,150             $3,400                $500' },
    ],
    sampleFigures: [],
  },
  {
    id: 'global-annual-report',
    title: 'Global Energy Corp Annual Sustainability Report',
    subtitle: 'Composite Corporate Publication with Sommaire & Infographics',
    tag: 'Sommaire & Composite Benchmark',
    type: 'Corporate Report',
    pageCount: 68,
    fileSize: '18.2 MB',
    description: 'Corporate report with a printed dot-leader Table of Contents on page 3, multiple sub-report sections, and sustainability charts.',
    natureProfile: {
      is_scanned: false,
      has_native_outline: false,
      has_sommaire: true,
      is_composite: true,
      has_rich_figures: true,
      has_tables_signal: true,
      label: 'native-sommaire',
      desc: 'Digital PDF with printed Table of Contents (dot-leader sommaire)',
    },
    metrics: {
      totalLines: 4850,
      totalSpans: 15200,
      linesPerPage: 71.32,
      nativeBookmarksCount: 0,
      figureCount: 34,
      tableCount: 18,
    },
    nativeBookmarks: [],
    sampleLines: [
      { page: 3, size: 14, font: 'Arial-Bold', flags: 16, text: 'TABLE OF CONTENTS' },
      { page: 3, size: 11, font: 'Arial', flags: 0, text: 'Executive Chairman Address ............................................ 4' },
      { page: 3, size: 11, font: 'Arial', flags: 0, text: 'Decarbonization Roadmap & Net-Zero Targets ............................ 12' },
      { page: 3, size: 11, font: 'Arial', flags: 0, text: 'Renewable Generation & Offshore Wind Assets ............................ 28' },
      { page: 3, size: 11, font: 'Arial', flags: 0, text: 'Consolidated ESG Performance Metrics .................................. 54' },
    ],
    sampleFigures: [
      { id: 'fig-esg-1', page: 12, title: 'Scope 1, 2, and 3 Greenhouse Gas Emissions Trajectory (2020-2035)', type: 'line_chart', summary: 'Projected emissions reductions showing 45% decline by 2030 across European operations.' },
    ],
  },
];
